### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by Thomas-Stussi**

### CODE REVIEW

**Comment by internetcharles** [comment]
this is the greatest readme i've ever seen

**Review by brookeperkins — COMMENTED** [review]
Fantastique!

**Review by Ryan-Diff — APPROVED** [review]

**Review by brookeperkins — APPROVED** [review]

**Review by internetcharles — APPROVED** [review]
it's just OK

**Comment by michmitz** [comment]
Dang this is amazing

**Pull request merged**
